---

- name: Ensure /usr/local/scripts exists
  file:
    dest: /usr/local/scripts
    state: directory
    mode: '0755'

- name: Ensure reporting script exists
  template:
    src: "{{ tinyproxy_reporting_template }}.j2"
    dest: "/usr/local/scripts/{{ tinyproxy_reporting_template | basename }}"
    mode: '0755'

- name: Add tinyproxy report in logrotate
  template:
    src: logrotate-tinyproxy.j2
    dest: /etc/logrotate.d/tinyproxy
    mode: '0644'
    validate: 'logrotate -dv %s'
