---

- name: Ensure /usr/local/scripts exists
  ansible.builtin.file:
    dest: /usr/local/scripts
    state: directory
    mode: '0755'

- name: Ensure reporting script exists
  ansible.builtin.template:
    src: "{{ tinyproxy_reporting_template }}.j2"
    dest: "/usr/local/scripts/{{ tinyproxy_reporting_template | basename }}"
    mode: '0755'

- name: Ensure logrotate package is present
  ansible.builtin.package:
    name: logrotate
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Add tinyproxy report in logrotate
  ansible.builtin.template:
    src: logrotate-tinyproxy.j2
    dest: /etc/logrotate.d/tinyproxy
    mode: '0644'
    validate: 'logrotate -dv %s'
