---

- name: Debian | Ensure apt is configured with proxy
  ansible.builtin.lineinfile:
    dest: /etc/apt/apt.conf.d/10proxy
    regexp: '^Acquire::http::Proxy ".*";'
    line: "Acquire::http::Proxy \"{{ tinyproxy_proxy_url }}\";"
    mode: '0644'
    create: yes
    backup: "{{ tinyproxy_backup | default(false) }}"
  when: ansible_os_family == "Debian"

- name: RedHat | Ensure dnf is configured with proxy
  community.general.ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: proxy
    value: "{{ tinyproxy_proxy_url }}"
    mode: '0600'
    backup: "{{ tinyproxy_backup | default(false) }}"
  with_items:
    - { o: proxy, v: "{{ tinyproxy_proxy_url }}" }
    - { o: proxy_username, v: "{{ tinyproxy_proxy_user | default(omit) }}" }
    - { o: proxy_password, v: "{{ tinyproxy_proxy_pass | default(omit) }}" }
  when: ansible_os_family == "RedHat"

- name: Linux | Update /etc/environment with proxy
  ansible.builtin.lineinfile:
    dest: /etc/environment
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
    mode: '0644'
  with_items:
    - { re: ^http_proxy=.*, l: "http_proxy={{ tinyproxy_proxy_url }}" }
    - { re: ^https_proxy=.*, l: "https_proxy={{ tinyproxy_proxy_url }}" }
    - { re: ^no_proxy=.*, l: "no_proxy={{ tinyproxy_no_proxy | default('127.0.0.1,::1,localhost,10.0.0.0/8,192.168.0.0/16') }}" }
  when: ansible_system == 'Linux'
