---

- name: Debian | update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: "{{ tinyproxy_apt_cache_valid | default('3600') }}"
  when: ansible_os_family == 'Debian'

- name: Install tinyproxy package
  ansible.builtin.package:
    name: tinyproxy
    state: present

- name: Tinyproxy filters
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/tinyproxy/{{ item | basename }}"
    mode: '0644'
  with_items: "{{ tinyproxy_filters }}"
  notify:
    - Restart tinyproxy

- name: Tinyproxy configuration
  ansible.builtin.template:
    src: "{{ tinyproxy_template }}.j2"
    dest: "{{ tinyproxy_conf }}"
    mode: '0644'
  notify:
    - Restart tinyproxy

- name: Ensure tinyproxy service is enabled
  ansible.builtin.service:
    name: tinyproxy
    enabled: "{{ tinyproxy_service_enable }}"

- name: Ensure log directory has right permissions
  ansible.builtin.file:
    path: "{{ tinyproxy_log | dirname }}"
    owner: "{{ tinyproxy_user }}"
    mode: "0755"
    state: directory

- import_tasks: systemd.yml
  when: tinyproxy_systemd_restriction_enable | bool and ansible_service_mgr == 'systemd'
