---

- name: Install tinyproxy package
  package:
    name: tinyproxy
    state: present

- name: tinyproxy filters
  template:
    src: "{{ item }}"
    dest: "/etc/tinyproxy/{{ item }}"
    mode: '0644'
  with_items: "{{ tinyproxy_filters }}"
  notify:
    - restart tinyproxy

- name: tinyproxy configuration
  template:
    src: "{{ tinyproxy_template }}.j2"
    dest: "{{ tinyproxy_conf }}"
    mode: '0644'
  notify:
    - restart tinyproxy

- name: Ensure tinyproxy service is enabled
  service:
    name: tinyproxy
    enabled: "{{ tinyproxy_service_enable }}"

- import_tasks: systemd.yml
  when: tinyproxy_systemd_restriction_enable|bool and ansible_service_mgr == 'systemd'
