---
# handlers file for juju4.tinyproxy

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )

- name: Restart tinyproxy
  ansible.builtin.service:
    name: tinyproxy
    state: restarted
  when: >
    not (ansible_virtualization_type is defined and
          (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
        )
