---

- name: Verify
  hosts: tinyproxy
  gather_facts: false
  tasks:
    - name: Debug | ansible_virtualization_type
      debug: var=ansible_virtualization_type verbosity=1
    - name: Gather package facts
      package_facts:
        manager: auto
    - name: Validate that needed packages are present
      assert:
        that: ansible_facts.packages['tinyproxy']

    - name: Ensure process is running
      command: pgrep -u _tinyproxy tinyproxy
      register: ps
      changed_when: false
      ignore_errors: true
    - name: Validate ps output
      assert:
        that: ps.stdout
      when: >
        not (ansible_virtualization_type is defined and
              (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
          )

    - name: Ensure ports are listening
      wait_for:
        host: "{{ item.h }}"
        port: "{{ item.p }}"
        timeout: 10
      with_items:
        - { h: localhost, p: 8888 }
      when: >
        not (ansible_virtualization_type is defined and
              (ansible_virtualization_type == "docker" or ansible_virtualization_type == "containerd")
          )
